version: 0.0
os: linux
files:
  - source: target/
    destination: /home/ec2-user/app/
hooks:
  BeforeInstall:
    - location: scripts/stop.sh
      runas: root
  AfterInstall:
    - location: scripts/start.sh
      runas: root
